# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(null=True)),
                ('empty_weight', models.FloatField(null=True)),
                ('full_weight', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('PAR', 'Part'), ('CON', 'Container'), ('TOO', 'Tool'), ('PRO', 'Prototype')], default='PAR', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
