# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20170328_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='weight',
        ),
        migrations.AddField(
            model_name='weight',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Box'),
        ),
    ]
