# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_auto_20170328_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
